services:
  mongo:
    image: mongo:8.0.12
    container_name: mongo-parcial
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: db_plant
    volumes:
      - mongo_data:/data/db

volumes:
    mongo_data: